name: Deploy to Remote Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy files to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_KEY }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        port: 22
        script: |
          cd /home/sahilr/the-Verge/
          git pull
          sudo systemctl restart verge.service